title: Constantine Nikolaou
description: Cloud Solution Architect, Software, Leadership, Digital Business Models, Startups and menadevs.com
show_downloads: false
google_analytics: UA-7598675-3
theme: jekyll-theme-minimal
